function codeGen(solver)
unknowns = [solver.OCP.lambda;...
            solver.OCP.mu;...
            solver.OCP.u;...
            solver.OCP.x;...
            solver.OCP.p];
if strcmp(solver.OCP.discretizationMethod,'Euler') && solver.OCP.isMEnabled == false
    switch solver.HessianApproximation
        case 'GaussNewton'
            A_ = solver.OCP.L;
        case 'GaussNewtonLC'
            A_ = solver.OCP.L + ...
                solver.OCP.mu.'*solver.OCP.C;
        case 'Newton'
            F = solver.OCP.f * solver.OCP.deltaTau - solver.OCP.x;
            A_ = solver.OCP.L + ...
                solver.OCP.mu.'*solver.OCP.C + ...
                solver.OCP.lambda.'*F;
        otherwise
            A_ = solver.OCP.L;
    end
else
    switch solver.HessianApproximation
        case 'GaussNewton'
            A_ = solver.OCP.L;
        case 'GaussNewtonLC'
            A_ = solver.OCP.L + ...
                solver.OCP.mu.'*solver.OCP.C;
        otherwise
            A_ = solver.OCP.L;
    end
end

A = symfun(A_,unknowns);
Au  = jacobian(A,solver.OCP.u);
Ax  = jacobian(A,solver.OCP.x);

Auu = jacobian(Au,solver.OCP.u);
Aux = jacobian(Au,solver.OCP.x);
Axx = jacobian(Ax,solver.OCP.x);
LambdaMuUXP = {solver.OCP.lambda;...
               solver.OCP.mu;...
               solver.OCP.u;...
               solver.OCP.x;...
               solver.OCP.p};
matlabFunction(Auu,...
    'File','./funcgen/OCP_GEN_Auu',...
    'Vars',LambdaMuUXP,...
        'Outputs',{'Auu'});

matlabFunction(Aux,...
    'File','./funcgen/OCP_GEN_Aux',...
    'Vars',LambdaMuUXP,...
        'Outputs',{'Aux'});

matlabFunction(Axx,...
    'File','./funcgen/OCP_GEN_Axx',...
    'Vars',LambdaMuUXP,...
        'Outputs',{'Axx'});

end