function codeGen(solver)
unknowns = [solver.OCP.lambda;...
            solver.OCP.mu;...
            solver.OCP.u;...
            solver.OCP.x;...
            solver.OCP.p;...
            solver.OCP.barrierPara];
        
LAll = solver.OCP.L + solver.OCP.LBarrier.all;

if  solver.OCP.isMEnabled == false
    switch solver.HessianApproximation
        case 'GaussNewton'
            A_ = LAll;
        case 'GaussNewtonLC'
            A_ = LAll + solver.OCP.mu.'*solver.OCP.C;
        case 'Newton'
            F = solver.OCP.f * solver.OCP.deltaTau - solver.OCP.x;
            A_ = LAll + solver.OCP.mu.'*solver.OCP.C + solver.OCP.lambda.'*F;
        otherwise
            A_ = LAll;
    end
else
    switch solver.HessianApproximation
        case 'GaussNewton'
            A_ = LAll;
        case 'GaussNewtonLC'
            A_ = LAll + solver.OCP.mu.'*solver.OCP.C;
        otherwise
            A_ = LAll;
    end
end
%% Generate Hessian for NMPC
A = symfun(A_,unknowns);
Au  = jacobian(A,solver.OCP.u);
Ax  = jacobian(A,solver.OCP.x);

Auu = jacobian(Au,solver.OCP.u);
Aux = jacobian(Au,solver.OCP.x);
Axx = jacobian(Ax,solver.OCP.x);
LambdaMuUXPBarrierPara = {solver.OCP.lambda;...
               solver.OCP.mu;...
               solver.OCP.u;...
               solver.OCP.x;...
               solver.OCP.p;...
               solver.OCP.barrierPara};
matlabFunction(Auu,...
    'File','./funcgen/OCP_GEN_Auu',...
    'Vars',LambdaMuUXPBarrierPara,...
        'Outputs',{'Auu'});

matlabFunction(Aux,...
    'File','./funcgen/OCP_GEN_Aux',...
    'Vars',LambdaMuUXPBarrierPara,...
        'Outputs',{'Aux'});

matlabFunction(Axx,...
    'File','./funcgen/OCP_GEN_Axx',...
    'Vars',LambdaMuUXPBarrierPara,...
        'Outputs',{'Axx'});
end