/*
 * File: FuncPlantSim.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 21-Jan-2018 01:45:16
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "ParNMPC.h"
#include "FuncPlantSim.h"
#include <stdio.h>
#include "omp.h"
#include "stdio.h"

/* Function Definitions */

/*
 * Arguments    : const double u[2]
 *                const double x[2]
 *                double Ts
 *                double xNext[2]
 * Return Type  : void
 */
void FuncPlantSim(const double u[2], const double x[2], double Ts, double xNext
                  [2])
{
  int i;
  double in1[4];
  double k1[2];
  double k2[2];
  double k3[2];
  for (i = 0; i < 2; i++) {
    in1[i] = u[i];
    in1[i + 2] = x[i];
  }

  /* GEN_FUNC_FSIM */
  /*     FSIM = GEN_FUNC_FSIM(IN1) */
  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     21-Jan-2018 01:44:51 */
  k1[0] = Ts * in1[3];
  k1[1] = Ts * (-in1[2] - in1[0] * in1[3]);
  for (i = 0; i < 2; i++) {
    in1[i] = u[i];
    in1[i + 2] = x[i] + k1[i] / 2.0;
  }

  /* GEN_FUNC_FSIM */
  /*     FSIM = GEN_FUNC_FSIM(IN1) */
  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     21-Jan-2018 01:44:51 */
  k2[0] = Ts * in1[3];
  k2[1] = Ts * (-in1[2] - in1[0] * in1[3]);
  for (i = 0; i < 2; i++) {
    in1[i] = u[i];
    in1[i + 2] = x[i] + k2[i] / 2.0;
  }

  /* GEN_FUNC_FSIM */
  /*     FSIM = GEN_FUNC_FSIM(IN1) */
  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     21-Jan-2018 01:44:51 */
  k3[0] = Ts * in1[3];
  k3[1] = Ts * (-in1[2] - in1[0] * in1[3]);
  for (i = 0; i < 2; i++) {
    in1[i] = u[i];
    in1[i + 2] = x[i] + k3[i];
  }

  /* GEN_FUNC_FSIM */
  /*     FSIM = GEN_FUNC_FSIM(IN1) */
  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     21-Jan-2018 01:44:51 */
  /*  update current state */
  xNext[0] = x[0] + (((k1[0] + 2.0 * k2[0]) + 2.0 * k3[0]) + Ts * in1[3]) / 6.0;
  xNext[1] = x[1] + (((k1[1] + 2.0 * k2[1]) + 2.0 * k3[1]) + Ts * (-in1[2] -
    in1[0] * in1[3])) / 6.0;
}

/*
 * File trailer for FuncPlantSim.c
 *
 * [EOF]
 */
