/*
 * File: GEN_Func_dKKT23_mu_u.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 21-Jan-2018 01:45:16
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "ParNMPC.h"
#include "GEN_Func_dKKT23_mu_u.h"
#include <stdio.h>
#include "omp.h"
#include "stdio.h"

/* Function Definitions */

/*
 * GEN_FUNC_DKKT23_MU_U
 *     DKKT23_MU_U = GEN_FUNC_DKKT23_MU_U(IN1,IN2)
 * Arguments    : const double in1[7]
 *                double dKKT23_mu_u[9]
 * Return Type  : void
 */
void GEN_Func_dKKT23_mu_u(const double in1[7], double dKKT23_mu_u[9])
{
  double t2;
  double t3;
  double t4;
  double x[9];

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     21-Jan-2018 01:44:51 */
  t2 = in1[3] * 0.16666666666666666;
  t3 = in1[4] * 0.16666666666666666;
  t4 = in1[2] * 0.16666666666666666;
  x[0] = 0.0;
  x[1] = t2;
  x[2] = t3;
  x[3] = t2;
  x[4] = t4 + 0.00083333333333333328;
  x[5] = 0.0;
  x[6] = t3;
  x[7] = 0.0;
  x[8] = t4 + 0.00083333333333333328;
  memcpy(&dKKT23_mu_u[0], &x[0], 9U * sizeof(double));
}

/*
 * File trailer for GEN_Func_dKKT23_mu_u.c
 *
 * [EOF]
 */
