/*
 * File: GEN_Func_KKT.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 21-Jan-2018 01:45:16
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "ParNMPC.h"
#include "GEN_Func_KKT.h"
#include <stdio.h>
#include "omp.h"
#include "stdio.h"

/* Function Definitions */

/*
 * GEN_FUNC_KKT
 *     KKT = GEN_FUNC_KKT(IN1,IN2,IN3,IN4)
 * Arguments    : const double in1[7]
 *                const double in2[2]
 *                const double in3[2]
 *                double KKT[7]
 * Return Type  : void
 */
void GEN_Func_KKT(const double in1[7], const double in2[2], const double in3[2],
                  double KKT[7])
{
  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     21-Jan-2018 01:44:50 */
  KKT[0] = (-in1[5] + in1[6] * 0.083333333333333329) + in2[0];
  KKT[1] = ((in1[5] * -0.083333333333333329 - in1[6]) + in2[1]) - in1[3] * in1[6]
    * 0.083333333333333329;
  KKT[2] = (in1[3] * in1[3] * 0.083333333333333329 + in1[4] * in1[4] *
            0.083333333333333329) - 0.083333333333333329;
  KKT[3] = (in1[3] * 0.00083333333333333328 + in1[2] * in1[3] *
            0.16666666666666666) - in1[1] * in1[6] * 0.083333333333333329;
  KKT[4] = (in1[4] * 0.00083333333333333328 + in1[2] * in1[4] *
            0.16666666666666666) - 0.005;
  KKT[5] = ((-in1[0] - in1[1] * 0.083333333333333329) + in3[0]) + in1[5] *
    0.83333333333333337;
  KKT[6] = (((in1[0] * 0.083333333333333329 - in1[1]) + in3[1]) + in1[6] *
            0.83333333333333337) - in1[1] * in1[3] * 0.083333333333333329;
}

/*
 * File trailer for GEN_Func_KKT.c
 *
 * [EOF]
 */
