function LAMBDA = getLAMBDA(solver,x0,lambda,mu,u,x,p)
xDim = solver.OCP.dim.x;
N    = solver.OCP.N;

LAMBDA = zeros(xDim,xDim,N);
[lambda,...
 mu,...
 u,...
 x,...
 LAMBDA,...
 cost,...
 error,...
 timeElapsed] = NMPC_Iter(x0,...
                          lambda,...
                          mu,...
                          u,...
                          x,...
                          p,...
                          LAMBDA);
end