function codeGen(plant)
    showInfo(plant);
    disp('Generating plant...');
    if ~plant.isMEnabled
       % init M
       plant.M = symfun(eye(plant.dim.x),[plant.u;plant.x;plant.p]);
    end
    matlabFunction(plant.f,...
        'File','./funcgen/SIM_GEN_f',...
        'Vars',{plant.u;plant.x;plant.p},...
        'Outputs',{'f'});
    
    matlabFunction(plant.M,...
        'File','./funcgen/SIM_GEN_M',...
        'Vars',{plant.u;plant.x;plant.p},...
        'Outputs',{'M'});
    disp('Done!')
end