/*
 * File: GEN_Func_fx_I.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 21-Jan-2018 02:13:18
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "ParNMPC.h"
#include "GEN_Func_fx_I.h"
#include <stdio.h>
#include "omp.h"
#include "stdio.h"

/* Function Definitions */

/*
 * GEN_FUNC_FX_I
 *     FX_I = GEN_FUNC_FX_I(IN1,IN2)
 * Arguments    : const double in1[30]
 *                double fx_I[81]
 * Return Type  : void
 */
void GEN_Func_fx_I(const double in1[30], double fx_I[81])
{
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t7;
  double t8;
  double t9;
  double x[81];

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     21-Jan-2018 02:12:06 */
  t2 = cos(in1[27]);
  t3 = cos(in1[29]);
  t4 = sin(in1[27]);
  t5 = sin(in1[28]);
  t6 = sin(in1[29]);
  t7 = cos(in1[28]);
  t8 = tan(in1[28]);
  t9 = t8 * t8;
  x[0] = -1.0;
  memset(&x[1], 0, sizeof(double) << 3);
  x[9] = 0.041666666666666664;
  x[10] = -1.0;
  memset(&x[11], 0, 9U * sizeof(double));
  x[20] = -1.0;
  memset(&x[21], 0, sizeof(double) << 3);
  x[29] = 0.041666666666666664;
  x[30] = -1.0;
  memset(&x[31], 0, 9U * sizeof(double));
  x[40] = -1.0;
  memset(&x[41], 0, sizeof(double) << 3);
  x[49] = 0.041666666666666664;
  x[50] = -1.0;
  x[51] = 0.0;
  x[52] = 0.0;
  x[53] = 0.0;
  x[54] = 0.0;
  x[55] = in1[13] * (t2 * t6 - t3 * t4 * t5) * 0.041666666666666664;
  x[56] = 0.0;
  x[57] = in1[13] * (t2 * t3 + t4 * t5 * t6) * -0.041666666666666664;
  x[58] = 0.0;
  x[59] = t4 * t7 * in1[13] * -0.041666666666666664;
  x[60] = (t2 * in1[15] * 0.041666666666666664 - t4 * in1[14] *
           0.041666666666666664) / t7 - 1.0;
  x[61] = t2 * in1[14] * -0.041666666666666664 - t4 * in1[15] *
    0.041666666666666664;
  x[62] = t2 * t8 * in1[15] * 0.041666666666666664 - t4 * t8 * in1[14] *
    0.041666666666666664;
  x[63] = 0.0;
  x[64] = t2 * t3 * t7 * in1[13] * 0.041666666666666664;
  x[65] = 0.0;
  x[66] = t2 * t6 * t7 * in1[13] * 0.041666666666666664;
  x[67] = 0.0;
  x[68] = t2 * t5 * in1[13] * -0.041666666666666664;
  x[69] = t5 / (t7 * t7) * (t2 * in1[14] + t4 * in1[15]) * 0.041666666666666664;
  x[70] = -1.0;
  x[71] = t2 * (t9 + 1.0) * in1[14] * 0.041666666666666664 + t4 * (t9 + 1.0) *
    in1[15] * 0.041666666666666664;
  x[72] = 0.0;
  x[73] = in1[13] * (t3 * t4 - t2 * t5 * t6) * 0.041666666666666664;
  x[74] = 0.0;
  x[75] = in1[13] * (t4 * t6 + t2 * t3 * t5) * 0.041666666666666664;
  x[76] = 0.0;
  x[77] = 0.0;
  x[78] = 0.0;
  x[79] = 0.0;
  x[80] = -1.0;
  memcpy(&fx_I[0], &x[0], 81U * sizeof(double));
}

/*
 * File trailer for GEN_Func_fx_I.c
 *
 * [EOF]
 */
