/*
 * File: GEN_Func_fu.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 21-Jan-2018 02:13:18
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "ParNMPC.h"
#include "GEN_Func_fu.h"
#include <stdio.h>
#include "omp.h"
#include "stdio.h"

/* Function Definitions */

/*
 * GEN_FUNC_FU
 *     FU = GEN_FUNC_FU(IN1,IN2)
 * Arguments    : const double in1[30]
 *                double fu[72]
 * Return Type  : void
 */
void GEN_Func_fu(const double in1[30], double fu[72])
{
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t7;
  double t8;
  double t9;
  double x[72];

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     21-Jan-2018 02:12:05 */
  t2 = cos(in1[29]);
  t3 = sin(in1[27]);
  t4 = cos(in1[27]);
  t5 = sin(in1[28]);
  t6 = sin(in1[29]);
  t7 = cos(in1[28]);
  t8 = 1.0 / t7;
  t9 = tan(in1[28]);
  x[0] = 0.0;
  x[1] = t3 * t6 * 0.041666666666666664 + t2 * t4 * t5 * 0.041666666666666664;
  x[2] = 0.0;
  x[3] = t2 * t3 * -0.041666666666666664 + t4 * t5 * t6 * 0.041666666666666664;
  x[4] = 0.0;
  x[5] = t4 * t7 * 0.041666666666666664;
  memset(&x[6], 0, 9U * sizeof(double));
  x[15] = t4 * t8 * 0.041666666666666664;
  x[16] = t3 * -0.041666666666666664;
  x[17] = t4 * t9 * 0.041666666666666664;
  x[18] = 0.0;
  x[19] = 0.0;
  x[20] = 0.0;
  x[21] = 0.0;
  x[22] = 0.0;
  x[23] = 0.0;
  x[24] = t3 * t8 * 0.041666666666666664;
  x[25] = t4 * 0.041666666666666664;
  x[26] = t3 * t9 * 0.041666666666666664;
  memset(&x[27], 0, sizeof(double) << 3);
  x[35] = 0.041666666666666664;
  memset(&x[36], 0, 36U * sizeof(double));
  memcpy(&fu[0], &x[0], 72U * sizeof(double));
}

/*
 * File trailer for GEN_Func_fu.c
 *
 * [EOF]
 */
