/*
 * File: GEN_Func_Hxx.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 21-Jan-2018 02:13:18
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "ParNMPC.h"
#include "GEN_Func_Hxx.h"
#include <stdio.h>
#include "omp.h"
#include "stdio.h"

/* Function Declarations */
static double rt_powd_snf(double u0, double u1);

/* Function Definitions */

/*
 * Arguments    : double u0
 *                double u1
 * Return Type  : double
 */
static double rt_powd_snf(double u0, double u1)
{
  double y;
  double d2;
  double d3;
  if (rtIsNaN(u0) || rtIsNaN(u1)) {
    y = rtNaN;
  } else {
    d2 = fabs(u0);
    d3 = fabs(u1);
    if (rtIsInf(u1)) {
      if (d2 == 1.0) {
        y = rtNaN;
      } else if (d2 > 1.0) {
        if (u1 > 0.0) {
          y = rtInf;
        } else {
          y = 0.0;
        }
      } else if (u1 > 0.0) {
        y = 0.0;
      } else {
        y = rtInf;
      }
    } else if (d3 == 0.0) {
      y = 1.0;
    } else if (d3 == 1.0) {
      if (u1 > 0.0) {
        y = u0;
      } else {
        y = 1.0 / u0;
      }
    } else if (u1 == 2.0) {
      y = u0 * u0;
    } else if ((u1 == 0.5) && (u0 >= 0.0)) {
      y = sqrt(u0);
    } else if ((u0 < 0.0) && (u1 > floor(u1))) {
      y = rtNaN;
    } else {
      y = pow(u0, u1);
    }
  }

  return y;
}

/*
 * GEN_FUNC_HXX
 *     HXX = GEN_FUNC_HXX(IN1,IN2)
 * Arguments    : const double in1[30]
 *                double Hxx[81]
 * Return Type  : void
 */
void GEN_Func_Hxx(const double in1[30], double Hxx[81])
{
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t7;
  double t8;
  double t9;
  double t12;
  double t20;
  double t21;
  double t24;
  double t32;
  double t34;
  double t37;
  double t40;
  double x[81];

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     21-Jan-2018 02:12:02 */
  t2 = tan(in1[28]);
  t3 = cos(in1[27]);
  t4 = sin(in1[27]);
  t5 = cos(in1[29]);
  t6 = sin(in1[28]);
  t7 = sin(in1[29]);
  t8 = cos(in1[28]);
  t9 = t2 * t2;
  t12 = t3 * in1[15] - t4 * in1[14];
  t20 = (((in1[8] * (t3 * (t2 * t2 + 1.0) * in1[15] - t4 * (t9 + 1.0) * in1[14])
           * 0.041666666666666664 + in1[5] * t4 * t6 * in1[13] *
           0.041666666666666664) + in1[6] * t6 * t12 * (1.0 / (t8 * t8)) *
          0.041666666666666664) - in1[1] * t4 * t5 * t8 * in1[13] *
         0.041666666666666664) - in1[3] * t4 * t7 * t8 * in1[13] *
    0.041666666666666664;
  t21 = 1.0 / t8;
  t24 = t3 * in1[14] + t4 * in1[15];
  t32 = in1[1] * (t3 * t5 + t4 * t6 * t7) * in1[13] * 0.041666666666666664 +
    in1[3] * (t3 * t7 - t4 * t5 * t6) * in1[13] * 0.041666666666666664;
  t34 = in1[3] * t3 * t5 * t8 * in1[13] * 0.041666666666666664 - in1[1] * t3 *
    t7 * t8 * in1[13] * 0.041666666666666664;
  t37 = t4 * t7 + t3 * t5 * t6;
  t40 = in1[3] * (t4 * t5 - t3 * t6 * t7) * in1[13] * 0.041666666666666664;
  x[0] = 0.41666666666666669;
  memset(&x[1], 0, 9U * sizeof(double));
  x[10] = 0.041666666666666664;
  memset(&x[11], 0, 9U * sizeof(double));
  x[20] = 0.083333333333333329;
  memset(&x[21], 0, 9U * sizeof(double));
  x[30] = 0.041666666666666664;
  memset(&x[31], 0, 9U * sizeof(double));
  x[40] = 0.41666666666666669;
  memset(&x[41], 0, 9U * sizeof(double));
  x[50] = 0.041666666666666664;
  memset(&x[51], 0, 9U * sizeof(double));
  x[60] = (((((t40 - in1[7] * t12 * 0.041666666666666664) - in1[8] * (t2 * t3 *
    in1[14] + t2 * t4 * in1[15]) * 0.041666666666666664) - in1[6] * t21 * t24 *
             0.041666666666666664) - in1[1] * t37 * in1[13] *
            0.041666666666666664) - in1[5] * t3 * t8 * in1[13] *
           0.041666666666666664) + 0.041666666666666664;
  x[61] = t20;
  x[62] = t32;
  x[63] = 0.0;
  x[64] = 0.0;
  x[65] = 0.0;
  x[66] = 0.0;
  x[67] = 0.0;
  x[68] = 0.0;
  x[69] = t20;
  x[70] = (((((in1[8] * (t2 * t3 * (t9 + 1.0) * in1[14] * 2.0 + t2 * t4 * (t9 +
    1.0) * in1[15] * 2.0) * 0.041666666666666664 + in1[6] * t21 * t24 *
               0.041666666666666664) - in1[5] * t3 * t8 * in1[13] *
              0.041666666666666664) + in1[6] * (t6 * t6) / rt_powd_snf(t8, 3.0) *
             t24 * 0.083333333333333329) - in1[1] * t3 * t5 * t6 * in1[13] *
            0.041666666666666664) - in1[3] * t3 * t6 * t7 * in1[13] *
           0.041666666666666664) + 0.041666666666666664;
  x[71] = t34;
  x[72] = 0.0;
  x[73] = 0.0;
  x[74] = 0.0;
  x[75] = 0.0;
  x[76] = 0.0;
  x[77] = 0.0;
  x[78] = t32;
  x[79] = t34;
  x[80] = (t40 - in1[1] * t37 * in1[13] * 0.041666666666666664) +
    0.041666666666666664;
  memcpy(&Hxx[0], &x[0], 81U * sizeof(double));
}

/*
 * File trailer for GEN_Func_Hxx.c
 *
 * [EOF]
 */
