/*
 * File: GEN_Func_Hux.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 21-Jan-2018 02:13:18
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "ParNMPC.h"
#include "GEN_Func_Hux.h"
#include <stdio.h>
#include "omp.h"
#include "stdio.h"

/* Function Definitions */

/*
 * GEN_FUNC_HUX
 *     HUX = GEN_FUNC_HUX(IN1,IN2)
 * Arguments    : const double in1[30]
 *                double Hux[72]
 * Return Type  : void
 */
void GEN_Func_Hux(const double in1[30], double Hux[72])
{
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t7;
  double t8;
  double t9;
  double t10;
  double t12;
  double x[72];

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     21-Jan-2018 02:12:06 */
  t2 = cos(in1[27]);
  t3 = cos(in1[29]);
  t4 = sin(in1[27]);
  t5 = sin(in1[28]);
  t6 = sin(in1[29]);
  t7 = cos(in1[28]);
  t8 = tan(in1[28]);
  t9 = 1.0 / t7;
  t10 = t8 * t8;
  t12 = 1.0 / (t7 * t7);
  memset(&x[0], 0, 48U * sizeof(double));
  x[48] = (in1[1] * (t2 * t6 - t3 * t4 * t5) * 0.041666666666666664 - in1[3] *
           (t2 * t3 + t4 * t5 * t6) * 0.041666666666666664) - in1[5] * t4 * t7 *
    0.041666666666666664;
  x[49] = (in1[7] * t2 * -0.041666666666666664 - in1[6] * t4 * t9 *
           0.041666666666666664) - in1[8] * t4 * t8 * 0.041666666666666664;
  x[50] = (in1[7] * t4 * -0.041666666666666664 + in1[6] * t2 * t9 *
           0.041666666666666664) + in1[8] * t2 * t8 * 0.041666666666666664;
  x[51] = 0.0;
  x[52] = 0.0;
  x[53] = 0.0;
  x[54] = 0.0;
  x[55] = 0.0;
  x[56] = (in1[5] * t2 * t5 * -0.041666666666666664 + in1[1] * t2 * t3 * t7 *
           0.041666666666666664) + in1[3] * t2 * t6 * t7 * 0.041666666666666664;
  x[57] = in1[8] * t2 * (t10 + 1.0) * 0.041666666666666664 + in1[6] * t2 * t5 *
    t12 * 0.041666666666666664;
  x[58] = in1[8] * t4 * (t10 + 1.0) * 0.041666666666666664 + in1[6] * t4 * t5 *
    t12 * 0.041666666666666664;
  x[59] = 0.0;
  x[60] = 0.0;
  x[61] = 0.0;
  x[62] = 0.0;
  x[63] = 0.0;
  x[64] = in1[1] * (t3 * t4 - t2 * t5 * t6) * 0.041666666666666664 + in1[3] *
    (t4 * t6 + t2 * t3 * t5) * 0.041666666666666664;
  x[65] = 0.0;
  x[66] = 0.0;
  x[67] = 0.0;
  x[68] = 0.0;
  x[69] = 0.0;
  x[70] = 0.0;
  x[71] = 0.0;
  memcpy(&Hux[0], &x[0], 72U * sizeof(double));
}

/*
 * File trailer for GEN_Func_Hux.c
 *
 * [EOF]
 */
