/*
 * File: GEN_Func_fSim.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 21-Jan-2018 02:13:18
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "ParNMPC.h"
#include "GEN_Func_fSim.h"
#include <stdio.h>
#include "omp.h"
#include "stdio.h"

/* Function Definitions */

/*
 * GEN_FUNC_FSIM
 *     FSIM = GEN_FUNC_FSIM(IN1)
 * Arguments    : const double in1[17]
 *                double fSim[9]
 * Return Type  : void
 */
void GEN_Func_fSim(const double in1[17], double fSim[9])
{
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t7;
  double t8;

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     21-Jan-2018 02:12:07 */
  t2 = cos(in1[16]);
  t3 = sin(in1[14]);
  t4 = cos(in1[14]);
  t5 = sin(in1[15]);
  t6 = sin(in1[16]);
  t7 = cos(in1[15]);
  t8 = tan(in1[15]);
  fSim[0] = in1[9];
  fSim[1] = in1[0] * (t3 * t6 + t2 * t4 * t5);
  fSim[2] = in1[11];
  fSim[3] = -in1[0] * (t2 * t3 - t4 * t5 * t6);
  fSim[4] = in1[13];
  fSim[5] = t4 * t7 * in1[0] - 9.81;
  fSim[6] = (t3 * in1[2] + t4 * in1[1]) / t7;
  fSim[7] = -t3 * in1[1] + t4 * in1[2];
  fSim[8] = (in1[3] + t3 * t8 * in1[2]) + t4 * t8 * in1[1];
}

/*
 * File trailer for GEN_Func_fSim.c
 *
 * [EOF]
 */
