/*
 * File: GEN_Func_dKKT23_mu_u.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 21-Jan-2018 02:13:18
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "ParNMPC.h"
#include "GEN_Func_dKKT23_mu_u.h"
#include <stdio.h>
#include "omp.h"
#include "stdio.h"

/* Function Definitions */

/*
 * GEN_FUNC_DKKT23_MU_U
 *     DKKT23_MU_U = GEN_FUNC_DKKT23_MU_U(IN1,IN2)
 * Arguments    : const double in1[30]
 *                double dKKT23_mu_u[144]
 * Return Type  : void
 */
void GEN_Func_dKKT23_mu_u(const double in1[30], double dKKT23_mu_u[144])
{
  double t2;
  double t4;
  double t5;
  double t6;
  double t7;
  double t8;
  double t9;
  double t10;
  double t11;
  double t12;
  double t13;
  double t14;
  double x[144];

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     21-Jan-2018 02:12:06 */
  t2 = in1[13] * 0.083333333333333329;
  t4 = in1[14] * 0.083333333333333329;
  t5 = in1[15] * 0.083333333333333329;
  t6 = in1[16] * 0.083333333333333329;
  t7 = in1[17] * 0.083333333333333329;
  t8 = in1[9] * 0.083333333333333329;
  t9 = in1[18] * 0.083333333333333329;
  t10 = in1[10] * 0.083333333333333329;
  t11 = in1[19] * 0.083333333333333329;
  t12 = in1[11] * 0.083333333333333329;
  t13 = in1[20] * 0.083333333333333329;
  t14 = in1[12] * 0.083333333333333329;
  x[0] = 0.0;
  x[1] = 0.0;
  x[2] = 0.0;
  x[3] = 0.0;
  x[4] = t2 - 0.45833333333333331;
  x[5] = 0.0;
  x[6] = 0.0;
  x[7] = 0.0;
  x[8] = t7;
  memset(&x[9], 0, sizeof(double) << 3);
  x[17] = t4;
  x[18] = 0.0;
  x[19] = 0.0;
  x[20] = 0.0;
  x[21] = t9;
  memset(&x[22], 0, sizeof(double) << 3);
  x[30] = t5;
  x[31] = 0.0;
  x[32] = 0.0;
  x[33] = 0.0;
  x[34] = t11;
  memset(&x[35], 0, sizeof(double) << 3);
  x[43] = t6;
  x[44] = 0.0;
  x[45] = 0.0;
  x[46] = 0.0;
  x[47] = t13;
  x[48] = t2 - 0.45833333333333331;
  x[49] = 0.0;
  x[50] = 0.0;
  x[51] = 0.0;
  x[52] = t8 + 0.041666666666666664;
  memset(&x[53], 0, sizeof(double) << 3);
  x[61] = t4;
  x[62] = 0.0;
  x[63] = 0.0;
  x[64] = 0.0;
  x[65] = t10 + 0.041666666666666664;
  memset(&x[66], 0, sizeof(double) << 3);
  x[74] = t5;
  x[75] = 0.0;
  x[76] = 0.0;
  x[77] = 0.0;
  x[78] = t12 + 0.041666666666666664;
  memset(&x[79], 0, sizeof(double) << 3);
  x[87] = t6;
  x[88] = 0.0;
  x[89] = 0.0;
  x[90] = 0.0;
  x[91] = t14 + 0.041666666666666664;
  x[92] = 0.0;
  x[93] = 0.0;
  x[94] = 0.0;
  x[95] = 0.0;
  x[96] = t7;
  x[97] = 0.0;
  x[98] = 0.0;
  x[99] = 0.0;
  x[100] = 0.0;
  x[101] = 0.0;
  x[102] = 0.0;
  x[103] = 0.0;
  x[104] = t8 + 0.00041666666666666669;
  x[105] = 0.0;
  x[106] = 0.0;
  x[107] = 0.0;
  x[108] = 0.0;
  x[109] = t9;
  x[110] = 0.0;
  x[111] = 0.0;
  x[112] = 0.0;
  x[113] = 0.0;
  x[114] = 0.0;
  x[115] = 0.0;
  x[116] = 0.0;
  x[117] = t10 + 0.00041666666666666669;
  x[118] = 0.0;
  x[119] = 0.0;
  x[120] = 0.0;
  x[121] = 0.0;
  x[122] = t11;
  x[123] = 0.0;
  x[124] = 0.0;
  x[125] = 0.0;
  x[126] = 0.0;
  x[127] = 0.0;
  x[128] = 0.0;
  x[129] = 0.0;
  x[130] = t12 + 0.00041666666666666669;
  x[131] = 0.0;
  x[132] = 0.0;
  x[133] = 0.0;
  x[134] = 0.0;
  x[135] = t13;
  x[136] = 0.0;
  x[137] = 0.0;
  x[138] = 0.0;
  x[139] = 0.0;
  x[140] = 0.0;
  x[141] = 0.0;
  x[142] = 0.0;
  x[143] = t14 + 0.00041666666666666669;
  memcpy(&dKKT23_mu_u[0], &x[0], 144U * sizeof(double));
}

/*
 * File trailer for GEN_Func_dKKT23_mu_u.c
 *
 * [EOF]
 */
