function codeGen(OCP)
    % init C if it is empty
    if OCP.dim.mu == 0
       OCP.C = symfun(zeros(OCP.dim.mu,1),[OCP.u;OCP.x;OCP.p]);
    end
    % init M if it is disabled
    if ~OCP.isMEnabled
       % init M
        OCP.M = symfun(eye(OCP.dim.x),[OCP.u;OCP.x;OCP.p]);
    end
    % L, Lu, Lx
    Lu = jacobian(OCP.L,OCP.u);
    Lx = jacobian(OCP.L,OCP.x);
    UXP = {OCP.u;OCP.x;OCP.p};
    matlabFunction(OCP.L,...
        'File','./funcgen/OCP_GEN_L',...
        'Vars',UXP,...
        'Outputs',{'L'});
    matlabFunction(Lu,...
    'File','./funcgen/OCP_GEN_Lu',...
    'Vars',UXP,...
    'Outputs',{'Lu'});
    matlabFunction(Lx,...
        'File','./funcgen/OCP_GEN_Lx',...
        'Vars',UXP,...
        'Outputs',{'Lx'});
    
    % C, Cu, Cx
    Cu = jacobian(OCP.C,OCP.u);
    Cx = jacobian(OCP.C,OCP.x);
    matlabFunction(OCP.C,...
    'File','./funcgen/OCP_GEN_C',...
    'Vars',UXP,...
        'Outputs',{'C'});
    matlabFunction(Cu,...
        'File','./funcgen/OCP_GEN_Cu',...
        'Vars',UXP,...
        'Outputs',{'Cu'});
    matlabFunction(Cx,...
        'File','./funcgen/OCP_GEN_Cx',...
        'Vars',UXP,...
        'Outputs',{'Cx'});
    
    % f, fu, fx, M(optional)
    fudt = jacobian(OCP.f*OCP.deltaTau,OCP.u);
    fxdt = jacobian(OCP.f*OCP.deltaTau,OCP.x);
    matlabFunction(OCP.f*OCP.deltaTau,...
    'File','./funcgen/OCP_GEN_fdt',...
    'Vars',UXP,...
        'Outputs',{'fdt'});
    matlabFunction(fudt,...
        'File','./funcgen/OCP_GEN_fudt',...
        'Vars',UXP,...
        'Outputs',{'fudt'});
    matlabFunction(fxdt,...
        'File','./funcgen/OCP_GEN_fxdt',...
        'Vars',UXP,...
        'Outputs',{'fxdt'});
    if OCP.isMEnabled
        matlabFunction(OCP.M,...
            'File','./funcgen/OCP_GEN_M',...
            'Vars',UXP,...
        'Outputs',{'M'});
        % Mx
        Mx = sym('Mx',[OCP.dim.x (OCP.dim.x*OCP.dim.x)]);
        for i = 1:OCP.dim.x
            Mx(:,(i-1)*OCP.dim.x+1:i*OCP.dim.x) = formula(diff(OCP.M,OCP.x(i)));
        end
        MxSymfun = symfun(Mx,[OCP.u;OCP.x;OCP.p]);
        matlabFunction(MxSymfun,...
            'File','./funcgen/OCP_GEN_Mx.m',...
            'Vars',UXP,...
            'Outputs',{'Mx'});
        % Mu
        Mu = sym('Mu',[OCP.dim.x (OCP.dim.x*OCP.dim.u)]);
        for i = 1:OCP.dim.u
            Mu(:,(i-1)*OCP.dim.x+1:i*OCP.dim.x) = formula(diff(OCP.M,OCP.u(i)));
        end
        MuSymfun = symfun(Mu,[OCP.u;OCP.x;OCP.p]);
        matlabFunction(MuSymfun,...
            'File','./funcgen/OCP_GEN_Mu.m',...
            'Vars',UXP,...
            'Outputs',{'Mu'});
    end
    %% OCP_F_Fu_Fx for code generation of OCP_KKTs and NMPC_Iter
    cfg_OCP_F_Fu_Fx = coder.config('lib');
    cfg_OCP_F_Fu_Fx.FilePartitionMethod = 'SingleFile';% single file
    cfg_OCP_F_Fu_Fx.BuildConfiguration = 'Faster Runs';
    cfg_OCP_F_Fu_Fx.TargetLang = 'C';
    cfg_OCP_F_Fu_Fx.SupportNonFinite = false;
    cfg_OCP_F_Fu_Fx.EnableOpenMP = true;
    cfg_OCP_F_Fu_Fx.GenerateExampleMain = 'DoNotGenerate';

    genArgs_F_Fu_Fx = {zeros(OCP.dim.u,1),...
                       zeros(OCP.dim.x,1),...
                       zeros(OCP.dim.p,1),...
                       coder.Constant(OCP.discretizationMethod),...
                       coder.Constant(OCP.isMEnabled)};
    codegen -config cfg_OCP_F_Fu_Fx...
             OCP_F_Fu_Fx...
             -args genArgs_F_Fu_Fx...
             -d codegen/lib/OCP_F_Fu_Fx
         
    %% OCP_KKTs to speedup fsolve
    cfg_OCP_KKTs = coder.config('mex');
    cfg_OCP_KKTs.CustomHeaderCode = '#include "OCP_F_Fu_Fx.h"';
    cfg_OCP_KKTs.FilePartitionMethod = 'SingleFile';% single file
    cfg_OCP_KKTs.TargetLang = 'C';
    include_path = '.\codegen\lib\OCP_F_Fu_Fx';
    cfg_OCP_KKTs.CustomInclude = include_path;
    cfg_OCP_KKTs.CustomSource = 'OCP_F_Fu_Fx.c';
    cfg_OCP_KKTs.EnableOpenMP = true;
    genArgs_OCP_KKTs = {zeros(OCP.N*OCP.dim.subDim,1)};
    global_values = {'pValGlobal', zeros(OCP.dim.p,OCP.N),...
                     'x0Global',   zeros(OCP.dim.x,1),...
                     'dimGlobal',  coder.Constant(OCP.dim),...
                     'isMEnabledGlobal',coder.Constant(OCP.isMEnabled),...
                     'discretizationMethodGlobal',coder.Constant(OCP.discretizationMethod),...
                     'NGlobal',coder.Constant(OCP.N)};
    codegen -config cfg_OCP_KKTs...
     OCP_KKTs...
    -args genArgs_OCP_KKTs...
    -global global_values...
    -d codegen/mex/OCP_KKTs
    clear OCP_KKTs_mex
end