/*
 * File: GEN_Func_fSim.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 21-Jan-2018 02:06:04
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "ParNMPC.h"
#include "GEN_Func_fSim.h"
#include <stdio.h>
#include "omp.h"
#include "stdio.h"

/* Function Definitions */

/*
 * GEN_FUNC_FSIM
 *     FSIM = GEN_FUNC_FSIM(IN1)
 * Arguments    : const double in1[8]
 *                double fSim[4]
 * Return Type  : void
 */
void GEN_Func_fSim(const double in1[8], double fSim[4])
{
  double t3;
  double t4;
  double t6;
  double t7;

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     21-Jan-2018 02:00:13 */
  t3 = 1.0 / (in1[6] + 273.15);
  t4 = exp(-(t3 * 9758.3));
  t6 = in1[4] * in1[4];
  t7 = exp(t3 * -8560.0);
  fSim[0] = (t6 * t7 * -9.043E+9 - t4 * in1[4] * 1.287E+12) - in1[0] * (in1[4] -
    5.1);
  fSim[1] = (t4 * in1[4] * 1.287E+12 - t4 * in1[5] * 1.287E+12) - in1[0] * in1[5];
  fSim[2] = ((((in1[6] * -30.828516377649329 + in1[7] * 30.828516377649329) + t6
               * t7 * 1.345865419699268E+11) - t4 * in1[4] *
              1.9223013845947041E+12) + t4 * in1[5] * 5.0345988644147E+12) -
    in1[0] * (in1[6] - 104.9);
  fSim[3] = (in1[1] * 0.1 + in1[6] * 86.688) - in1[7] * 86.688;
}

/*
 * File trailer for GEN_Func_fSim.c
 *
 * [EOF]
 */
