/*
 * File: GEN_Func_Hxdt.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 21-Jan-2018 02:06:04
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "ParNMPC.h"
#include "GEN_Func_Hxdt.h"
#include <stdio.h>
#include "omp.h"
#include "stdio.h"

/* Function Definitions */

/*
 * GEN_FUNC_HXDT
 *     OUT1 = GEN_FUNC_HXDT(IN1,IN2)
 * Arguments    : const double in1[14]
 *                double out1[4]
 * Return Type  : void
 */
void GEN_Func_Hxdt(const double in1[14], double out1[4])
{
  double t3;
  double t4;
  double t5;
  double t7;
  double t8;
  double t9;
  double t11;
  double t12;

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     21-Jan-2018 02:00:11 */
  t3 = 1.0 / (in1[12] + 273.15);
  t4 = exp(-(t3 * 9758.3));
  t5 = exp(-(t3 * 8560.0));
  t7 = t4 * 1.287E+12;
  t8 = 1.0 / ((in1[12] + 273.15) * (in1[12] + 273.15));
  t9 = t4 * t8 * in1[10] * 1.25589321E+16;
  t11 = in1[10] * in1[10];
  t12 = in1[3] * 1.505;
  out1[0] = (((in1[10] * 0.003472222222222222 + in1[1] * t4 * 2.234375E+10) -
              in1[0] * ((t7 + in1[6]) + t5 * in1[10] * 1.8086E+10) *
              0.017361111111111112) - in1[2] * (t4 * 1.9223013845947041E+12 - t5
              * in1[10] * 2.691730839398537E+11) * 0.017361111111111112) -
    0.00743125;
  out1[1] = ((in1[11] * 0.017361111111111112 - in1[1] * (t7 + in1[6]) *
              0.017361111111111112) + in1[2] * t4 * 8.7406230284977432E+10) -
    0.018928819444444439;
  out1[2] = ((((t12 + in1[12] * 0.0086805555555555559) - in1[0] * (t9 + t5 * t8 *
    t11 * 7.740808E+13) * 0.017361111111111112) + in1[1] * (t9 - t4 * t8 * in1
    [11] * 1.25589321E+16) * 0.017361111111111112) - in1[2] * ((((in1[6] - t5 *
    t8 * t11 * 1.152060799262574E+15) + t4 * t8 * in1[10] * 1.87583936012905E+16)
    - t4 * t8 * in1[11] * 4.9129126098617968E+16) + 30.828516377649329) *
             0.017361111111111112) - 0.99123263888888891;
  out1[3] = ((in1[2] * 0.53521729822307862 - t12) + in1[13] *
             0.003472222222222222) - 0.39204861111111111;
}

/*
 * File trailer for GEN_Func_Hxdt.c
 *
 * [EOF]
 */
