/*
 * File: GEN_Func_fu.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 21-Jan-2018 02:06:04
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "ParNMPC.h"
#include "GEN_Func_fu.h"
#include <stdio.h>
#include "omp.h"
#include "stdio.h"

/* Function Definitions */

/*
 * GEN_FUNC_FU
 *     FU = GEN_FUNC_FU(IN1,IN2)
 * Arguments    : const double in1[14]
 *                double fu[16]
 * Return Type  : void
 */
void GEN_Func_fu(const double in1[14], double fu[16])
{
  double x[16];

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     21-Jan-2018 02:00:12 */
  x[0] = in1[10] * -0.017361111111111112 + 0.088541666666666671;
  x[1] = in1[11] * -0.017361111111111112;
  x[2] = in1[12] * -0.017361111111111112 + 1.821180555555556;
  x[3] = 0.0;
  x[4] = 0.0;
  x[5] = 0.0;
  x[6] = 0.0;
  x[7] = 0.001736111111111111;
  memset(&x[8], 0, sizeof(double) << 3);
  memcpy(&fu[0], &x[0], sizeof(double) << 4);
}

/*
 * File trailer for GEN_Func_fu.c
 *
 * [EOF]
 */
