/*
 * File: GEN_Func_dKKT23_mu_u.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 21-Jan-2018 02:06:04
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "ParNMPC.h"
#include "GEN_Func_dKKT23_mu_u.h"
#include <stdio.h>
#include "omp.h"
#include "stdio.h"

/* Function Definitions */

/*
 * GEN_FUNC_DKKT23_MU_U
 *     DKKT23_MU_U = GEN_FUNC_DKKT23_MU_U(IN1,IN2)
 * Arguments    : const double in1[14]
 *                double dKKT23_mu_u[36]
 * Return Type  : void
 */
void GEN_Func_dKKT23_mu_u(const double in1[14], double dKKT23_mu_u[36])
{
  double t2;
  double t4;
  double t6;
  double t7;
  double t9;
  double t10;
  double x[36];

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     21-Jan-2018 02:00:12 */
  t2 = in1[6] * 0.034722222222222224;
  t4 = in1[7] * 0.034722222222222224;
  t6 = in1[8] * 0.034722222222222224;
  t7 = in1[4] * 0.034722222222222224;
  t9 = in1[9] * 0.034722222222222224;
  t10 = in1[5] * 0.034722222222222224;
  x[0] = 0.0;
  x[1] = 0.0;
  x[2] = t2 - 0.60763888888888884;
  x[3] = 0.0;
  x[4] = t6;
  x[5] = 0.0;
  x[6] = 0.0;
  x[7] = 0.0;
  x[8] = 0.0;
  x[9] = t4 + 156.25;
  x[10] = 0.0;
  x[11] = t9;
  x[12] = t2 - 0.60763888888888884;
  x[13] = 0.0;
  x[14] = t7 + 0.0086805555555555559;
  x[15] = 0.0;
  x[16] = 0.0;
  x[17] = 0.0;
  x[18] = 0.0;
  x[19] = t4 + 156.25;
  x[20] = 0.0;
  x[21] = t10 + 8.680555555555555E-9;
  x[22] = 0.0;
  x[23] = 0.0;
  x[24] = t6;
  x[25] = 0.0;
  x[26] = 0.0;
  x[27] = 0.0;
  x[28] = t7 + 0.0086805555555555559;
  x[29] = 0.0;
  x[30] = 0.0;
  x[31] = t9;
  x[32] = 0.0;
  x[33] = 0.0;
  x[34] = 0.0;
  x[35] = t10 + 8.680555555555555E-9;
  memcpy(&dKKT23_mu_u[0], &x[0], 36U * sizeof(double));
}

/*
 * File trailer for GEN_Func_dKKT23_mu_u.c
 *
 * [EOF]
 */
