/*
 * File: GEN_Func_Hux.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 21-Jan-2018 01:36:29
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "ParNMPC.h"
#include "GEN_Func_Hux.h"
#include <stdio.h>
#include "omp.h"
#include "stdio.h"

/* Function Definitions */

/*
 * GEN_FUNC_HUX
 *     HUX = GEN_FUNC_HUX(IN1,IN2)
 * Arguments    : const double in1[15]
 *                double Hux[12]
 * Return Type  : void
 */
void GEN_Func_Hux(const double in1[15], double Hux[12])
{
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t7;
  double t12;
  double t14;
  double t15;
  double t18;
  double t22;
  double t19;
  double t20;
  double t23;
  double t24;
  double t26;
  double t28;
  double t30;
  double t31;
  double x[12];

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     21-Jan-2018 01:32:06 */
  t2 = cos(in1[9]);
  t3 = cos(in1[10]);
  t4 = in1[9] - in1[10];
  t5 = cos(t4);
  t6 = sin(in1[9]);
  t7 = sin(t4);
  t12 = t5 * t5;
  t14 = (((t2 * t2 * 972.0 + t3 * t3 * 345.0) + t12 * 1035.0) - t2 * t3 * t5 *
         810.0) - 2116.0;
  t15 = 1.0 / t14;
  t18 = t5 * t7 * 2070.0;
  t22 = t2 * t3 * t7 * 810.0;
  t19 = ((t2 * t6 * 1944.0 + t18) - t3 * t5 * t6 * 810.0) - t22;
  t20 = 1.0 / (t14 * t14);
  t23 = t2 * t7 * 54000.0;
  t24 = sin(in1[10]);
  t26 = t2 * 24000.0 - t3 * t5 * 10000.0;
  t28 = t3 * 46000.0 - t2 * t5 * 54000.0;
  t30 = ((t18 - t22) + t2 * t5 * t24 * 810.0) - t3 * t24 * 690.0;
  t31 = t12 * 90000.0;
  x[0] = ((((in1[5] * t15 * (t23 + t5 * t6 * 54000.0) * 0.0027777777777777779 -
             in1[4] * t15 * (t6 * 24000.0 - t3 * t7 * 10000.0) * 0.00625) - in1
            [3] * t5 * t7 * t15 * 37.5) + in1[4] * t19 * t20 * t26 * 0.00625) +
          in1[5] * t19 * t20 * t28 * 0.0027777777777777779) + in1[3] * t19 * t20
    * (t31 - 184000.0) * 0.00020833333333333329;
  x[1] = 0.0;
  x[2] = ((((in1[4] * t15 * (t3 * t7 * 10000.0 - t5 * t24 * 10000.0) * -0.00625
             - in1[5] * t15 * (t23 + t24 * 46000.0) * 0.0027777777777777779) +
            in1[3] * t5 * t7 * t15 * 37.5) - in1[4] * t20 * t26 * t30 * 0.00625)
          - in1[5] * t20 * t28 * t30 * 0.0027777777777777779) - in1[3] * t20 *
    t30 * (t31 - 184000.0) * 0.00020833333333333329;
  memset(&x[3], 0, 9U * sizeof(double));
  memcpy(&Hux[0], &x[0], 12U * sizeof(double));
}

/*
 * File trailer for GEN_Func_Hux.c
 *
 * [EOF]
 */
