/*
 * File: GEN_Func_dKKT23_mu_u.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 21-Jan-2018 01:36:29
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "ParNMPC.h"
#include "GEN_Func_dKKT23_mu_u.h"
#include <stdio.h>
#include "omp.h"
#include "stdio.h"

/* Function Definitions */

/*
 * GEN_FUNC_DKKT23_MU_U
 *     DKKT23_MU_U = GEN_FUNC_DKKT23_MU_U(IN1,IN2)
 * Arguments    : const double in1[15]
 *                const double in2[8]
 *                double dKKT23_mu_u[9]
 * Return Type  : void
 */
void GEN_Func_dKKT23_mu_u(const double in1[15], const double in2[8], double
  dKKT23_mu_u[9])
{
  double t2;
  double t3;
  double t4;
  double x[9];

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     21-Jan-2018 01:32:06 */
  t2 = in1[7] * 0.083333333333333329;
  t3 = in1[8] * 0.083333333333333329;
  t4 = in1[6] * 0.083333333333333329;
  x[0] = 0.0;
  x[1] = t2;
  x[2] = t3;
  x[3] = t2;
  x[4] = in2[6] * 0.041666666666666664 + t4;
  x[5] = 0.0;
  x[6] = t3;
  x[7] = 0.0;
  x[8] = in2[7] * 0.041666666666666664 + t4;
  memcpy(&dKKT23_mu_u[0], &x[0], 9U * sizeof(double));
}

/*
 * File trailer for GEN_Func_dKKT23_mu_u.c
 *
 * [EOF]
 */
