/*
 * File: GEN_Func_fSim.c
 *
 * MATLAB Coder version            : 3.1
 * C/C++ source code generated on  : 21-Jan-2018 01:36:29
 */

/* Include Files */
#include "rt_nonfinite.h"
#include "ParNMPC.h"
#include "GEN_Func_fSim.h"
#include <stdio.h>
#include "omp.h"
#include "stdio.h"

/* Function Definitions */

/*
 * GEN_FUNC_FSIM
 *     FSIM = GEN_FUNC_FSIM(IN1)
 * Arguments    : const double in1[8]
 *                double fSim[6]
 * Return Type  : void
 */
void GEN_Func_fSim(const double in1[8], double fSim[6])
{
  double t2;
  double t3;
  double t5;
  double t4;
  double t6;
  double t7;
  double t8;
  double t9;
  double t10;
  double t12;
  double t16;

  /*     This function was generated by the Symbolic Math Toolbox version 7.0. */
  /*     21-Jan-2018 01:32:06 */
  t2 = cos(in1[2]);
  t3 = cos(in1[3]);
  t5 = in1[2] - in1[3];
  t4 = cos(t5);
  t6 = t4 * t4;
  t7 = sin(in1[3]);
  t8 = sin(in1[2]);
  t9 = sin(t5);
  t10 = t2 * t2;
  t12 = t3 * t3;
  t16 = 1.0 / ((((t10 * 972.0 + t12 * 345.0) + t6 * 1035.0) - t2 * t3 * t4 *
                810.0) - 2116.0);
  fSim[0] = in1[5];
  fSim[1] = in1[6];
  fSim[2] = in1[7];
  fSim[3] = t16 * (((((((((((((in1[0] * 184000.0 - t2 * t8 * 1.907064E+6) - t3 *
    t7 * 676890.0) - t6 * in1[0] * 90000.0) + t2 * t4 * t7 * 794610.0) + t3 * t4
    * t8 * 794610.0) + t8 * in1[5] * in1[6] * 49680.0) + t7 * in1[6] * in1[7] *
    20700.0) - t3 * t9 * in1[5] * in1[6] * 20700.0) + t2 * t9 * in1[6] * in1[7] *
                       24300.0) - t6 * t8 * in1[5] * in1[6] * 24300.0) - t6 * t7
                     * in1[6] * in1[7] * 10125.0) + t2 * t4 * t9 * in1[5] * in1
                    [6] * 24300.0) - t3 * t4 * t9 * in1[6] * in1[7] * 10125.0) *
    -0.005;
  fSim[4] = t16 * (((((((((((((t8 * 541512.0 - t4 * t7 * 225630.0) - t8 * t12 *
    88290.0) - t2 * in1[0] * 24000.0) + t2 * t3 * t7 * 88290.0) + t3 * t4 * in1
    [0] * 10000.0) - t9 * in1[6] * in1[7] * 6900.0) - t2 * t8 * in1[5] * in1[6] *
    6480.0) - t2 * t7 * in1[6] * in1[7] * 2700.0) - t4 * t9 * in1[5] * in1[6] *
                       6900.0) + t9 * t12 * in1[6] * in1[7] * 1125.0) + t2 * t3 *
                     t9 * in1[5] * in1[6] * 2700.0) + t3 * t4 * t8 * in1[5] *
                    in1[6] * 2700.0) + t3 * t4 * t7 * in1[6] * in1[7] * 1125.0) *
    -0.15;
  fSim[5] = t16 * (((((((((((((t7 * 1.037898E+6 - t4 * t8 * 1.218402E+6) - t7 *
    t10 * 476766.0) - t3 * in1[0] * 46000.0) + t2 * t3 * t8 * 476766.0) + t2 *
    t4 * in1[0] * 54000.0) + t9 * in1[5] * in1[6] * 31740.0) - t3 * t8 * in1[5] *
    in1[6] * 12420.0) - t3 * t7 * in1[6] * in1[7] * 5175.0) + t4 * t9 * in1[6] *
                       in1[7] * 15525.0) - t9 * t10 * in1[5] * in1[6] * 14580.0)
                     + t2 * t4 * t8 * in1[5] * in1[6] * 14580.0) + t2 * t4 * t7 *
                    in1[6] * in1[7] * 6075.0) - t2 * t3 * t9 * in1[6] * in1[7] *
                   6075.0) * -0.066666666666666666;
}

/*
 * File trailer for GEN_Func_fSim.c
 *
 * [EOF]
 */
